---
- name: Checking for required variables
  fail: msg="Bailing out. A scout_account_key is required." 
  when: scout_account_key is not defined
  tags: [ 'monitoring', 'scout' ]

- name: Install the Ubuntu apt-key
  apt_key: url=https://archive.scoutapp.com/scout-archive.key
  when: ansible_distribution == 'Ubuntu'
  tags: [ 'monitoring', 'scout' ]

- name: Set up the scout apt repository
  apt_repository: repo='deb http://archive.scoutapp.com ubuntu main'
  when: ansible_distribution == 'Ubuntu'
  tags: [ 'monitoring', 'scout' ]

- name: install the scoutd package deps
  apt: name={{ item }} state=present
  with_items:
    - ruby
    - ruby-dev
  when: ansible_distribution == 'Ubuntu'
  notify: restart scout
  tags: [ 'monitoring', 'scout' ]

- name: install the scoutd package
  apt: name=scoutd state=present
  when: ansible_distribution == 'Ubuntu'
  notify: restart scout
  tags: [ 'monitoring', 'scout' ]

- name: Install python-gnupg
  yum: name=python-gnupg
  when: ansible_distribution == "Fedora"
  notify: restart scout
  tags: [ 'monitoring', 'scout' ]

- name: Install the RedHat GPG key
  rpm_key: state=present key=https://archive.scoutapp.com/RPM-GPG-KEY-scout
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS" or ansible_distribution == "Fedora"
  tags: [ 'monitoring', 'scout' ]

- name: Set up the scout yum repository
  get_url: url=https://archive.scoutapp.com/yum.repos.d/scout-rhel.repo dest=/etc/yum.repos.d/scout.repo
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "Centos"
  tags: [ 'monitoring', 'scout' ]

- name: Set up the scout yum repository
  get_url: url=https://archive.scoutapp.com/yum.repos.d/scout-fedora.repo dest=/etc/yum.repos.d/scout.repo
  when: ansible_distribution == "Fedora"
  tags: [ 'monitoring', 'scout' ]

- name: Install the scoutd package
  yum: name=scoutd state=latest
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS" or ansible_distribution == "Fedora"
  notify: restart scout
  tags: [ 'monitoring', 'scout' ]

- name: Ensure the directory for the public key exists
  file: path=/var/lib/scoutd
          owner=scoutd
          group=scoutd
          state=directory
  tags: [ 'monitoring', 'scout' ]

- name: Install libselinux-python bindings
  yum: name=libselinux-python state=present
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"
  notify: restart scout
  tags: [ 'monitoring', 'scout' ]

- name: Copy scout_rsa.pub to the /var/lib/scoutd directory
  template: src=scout_rsa.pub dest=/var/lib/scoutd/scout_rsa.pub owner=scoutd group=scoutd mode=0600
  notify: restart scout
  tags: [ 'monitoring', 'scout' ]

- name: Set up scout config file
  template: src=scoutd.yml dest=/etc/scout/scoutd.yml owner=scoutd group=scoutd
  notify: restart scout
  tags: [ 'monitoring', 'scout' ]

- name: Create systemd service file
  template:
    src=scoutd.service.j2
    dest=/etc/systemd/system/scoutd.service
    owner=root
    group=root
    mode=0644
  when: ansible_service_mgr == "systemd"
  notify: restart scout
  tags: [ 'monitoring', 'scout' ]