---
- name: Checking for required variables
  fail: msg="Bailing out. A scout_account_key is required." 
  when: scout_account_key is not defined 

- name: Install the apt-key for the scout repository
  apt_key: url=https://archive.scoutapp.com/scout-archive.key

- name: Set up the scout apt repository
  apt_repository: repo='deb http://archive.scoutapp.com ubuntu main'

- name: install the scoutd package
  apt: name=scoutd state=present

- name: Ensure the directory for the public key exists
  file: path=/var/lib/scoutd/.scout
          owner=scoutd
          group=scoutd
          state=directory

- name: Copy scout_rsa.pub to the /var/lib/scoutd/.scout directory
  copy: src=scout_rsa.pub dest=/var/lib/scoutd/.scout owner=scoutd group=scoutd mode=0644

- name: Set up scout config file
  template: src=scoutd.yml dest=/etc/scout/scoutd.yml owner=scoutd group=scoutd
  notify: restart scout
